### DISCUSSION TITLE
Mono Repo overlapping content

### DISCUSSION THREAD

**Discussion by dhrudevaliasolidatus** [GitbookIO/community#351] [3. Git Sync]
## Issue
We are trying to enable/setup mono repo support for our repo.
Our current structure looks like

/docs/.*

We have 2 different build scripts that select different parts of each doc.
i.e. 
Doc A = 
- ./docs/A.md
- ./docs/B.md
- ./docs/C.md

Doc B = 
- ./docs/A.md
- ./docs/D.md
- ./docs/E.md

Since each Space requires a separate .gitbook.yaml for the git sync, and they cannot overlap we are unsure how to set this up.

Initial tests
1. Create a .gitbook folder at root level
2. Create .gitbook/A/.gitbook.yaml
3. Create .gitbook/B/.gitbook.yaml]
4. Each GitSync points to .gitbook/A/ and .gitbook/B/
5. Content of each .yaml looks like
```
root: ../../docs
structure:
  readme: ./A.md
  summary: ./summary.md
```
However it seems that relative back paths do not work and we get a git sync timeout.

Alternative Test
1. Have .gitbook.yaml A in the root of the repo at ./
2. Create another .gitbook.yaml in ./docs/
3. Point each gitSync at ./ and ./docs/
4. Yaml content looks like
For root .gitbook.yaml
```
root: ./docs
structure:
  readme: ./A.md
  summary: ./summary.md
```

For ./docs/.gitbook.yaml
```
root: ./
-- since already in ./docs
structure:
  readme: ./A.md
  summary: ./summary.md
```

This also didn't work.

Is there a recommended way to have overlapping content in git syncs for 2 different spaces. The guess is that it is failing either on the `../` relative path for the root, or it is failing when there are 2 gitbook.yamls in subfolders.
