### DISCUSSION TITLE
New Open API block is great but need improvements

### DISCUSSION THREAD

**Discussion by rocchisanijl** [GitbookIO/community#560] [4. Open API]
Hello 

Thank you for having develop this new OpenAPI block this is really appreciated but I would suggest the following improvements:

1. add more languages than Curl and Javascript and espacially server side ones like Python, node.js, Java, PHP ... or use AI to translate from  a language to another one
2. add input fields for parameters (headers, query ...) of the request that update dynamically the snippet example
3. initiate "test-it" function with sample values of the request if present like in the snippet
4. "test-it" function seems not taking account security scheme oauth2
```
  securitySchemes:
    oauth-flows:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: >-
            https://api.scalexpert.hml.societegenerale.com/baas/uat/auth-server/api/v1/oauth2/token
          scopes:
            'e-financing:rw': ''
```
5. make the response snipet dynamic according the choice of the http response (200,400, 401 ...) 
6. taking account many samples of request and response if mentioned in the openapi file.
7. add a block description of the OpenAPi file is present in OpenAPI file
