### DISCUSSION TITLE
Integration failed to process the request

### DISCUSSION THREAD

**Discussion by Code-Milker** [GitbookIO/community#716] [0. General bugs and questions]
# GitBook Integration Issue

## Issue:

When I load my integration into my GitBook space, I receive the following error:

```json
{
  "code": 400,
  "message": "Integration failed to process the request"
}
```

## Request URL:

```text
https://api.gitbook.com/v1/integrations/blendin-demo-intergration/render?request=N4Igxg9gtgDhB2BTeAXAkgExALhDAlmANaIBOIANHqRDAM47AC%2BVkqiAHioyCgJ4xEOEBghgArlGTcqiDPhQBDAEYAbIdhSlxiKnRiKwiTMIByAZQDiUACoBGOhACyAYQBuAKQAMAcxjmARQB5FwAmSl4AC0QpYQxFUiIQJiYgA
```

## `src/index.tsx`

```typescript
import { createIntegration, createComponent } from "@gitbook/runtime";

const component = createComponent({
  componentId: 'unique-id',
  initialState: (props) => ({ message: 'Click me' }),
  action: async (element, action, context) => {
    return { state: { message: 'Hello world' } };
  },
  render: async (element, action, context) => {
    return (
      <block>
        <button label={element.state.message} onPress={{ action: 'say' }} />
      </block>
    );
  },
});

export default createIntegration({
  fetch: (e, a, c) => { console.log('hello?'); },
  components: [component],
});
```

## `package.json`

```json
{
  "name": "gitbook-blendin-locale",
  "private": true,
  "scripts": {
    "lint": "eslint --ext .js,.jsx,.ts,.tsx .",
    "typecheck": "tsc --noEmit",
    "publish": "gitbook publish ."
  },
  "dependencies": {
    "@gitbook/runtime": "*"
  },
  "devDependencies": {
    "@gitbook/cli": "^0.17.0",
    "@gitbook/eslint-config": "*",
    "@gitbook/tsconfig": "*",
    "typescript": "^5.6.2"
  }
}
```

## `gitbook-manifest.yaml`

```yaml
name: blendin-demo-intergration
title: Gitbook Demo Integration
organization: tkmAOqkd4s0l4yx8tYS9
visibility: public
description: ''
script: src/index.tsx
scopes:
  - space:content:read
  - space:content:write
  - space:metadata:read
  - space:metadata:write
  - space:views:read
blocks:
  - id: picker
    title: help me
    description: A block that allows users to switch between locales in GitBook.
secrets: {}
```

## `.gitbook-dev.yaml`

```yaml
space: NSGmT1soMCvJ0gpSQOC2
```

## Problem:

I'm able to publish the integration to my organization and add it to my space, but it immediately errors out with a 400 error upon being added. Any suggestions or insights into what might be going wrong would be appreciated!
