### DISCUSSION TITLE
Authorization scheme not showing in OpenAPI block

### DISCUSSION THREAD

**Discussion by livingos** [GitbookIO/community#854] [4. Open API]
I have been trying to use the OpenAPI blocks to provide documentation for an APi.

Despite there being a securityScheme defined and set to be default for all endpoints, the blocks in GitBook do not show Authorization element. I have seen examples from others that do, though other issues have been reported that they don't insert appropriate headers in examples.

In my openapi yaml I have:

```
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
security:
  -
    default: []
```

They show correctly in other tools such as scalar and elements, where appropriate auth elements are shown, but here in gitbook I don't get any authorization details:
![Screenshot 2025-01-21 at 15 52 21](https://github.com/user-attachments/assets/ac57f7a6-2238-45a1-86be-c9006768228c)
