### DISCUSSION TITLE
OpenAPI - support for relative documents with embedded schema

### DISCUSSION THREAD

**Discussion by System-Glitch** [GitbookIO/community#858] [4. Open API] [answered]
Hello, the OpenAPI integration is a really useful feature. We would like to use it. However, due to the size of our spec, we split it in several files using relative document refs, like so:

```yml
paths:
  /profile:
    $ref: "./paths/profile.yml#/components/pathItems/profile"
```

This is described as valid in the [OpenAPI spec](https://swagger.io/specification/), under the "Reference Object -> Relative Documents with Embedded Schema Example".

Is it supported by Gitbook? If yes, how do you make it work? I can only select one file per OpenAPI block. When they use a relative document ref, the block appears either empty or with ref errors.

If it's not supported, are there any plans?
